---
- name: Ensure target directory exists
  ansible.builtin.file:
    path: "/tmp/filebeat"
    state: directory
    mode: 0700

- name: Copy filebeat.yaml.j2 template to remote
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/filebeat/filebeat.yaml.j2"
    dest: "/tmp/filebeat/filebeat.yaml.j2"
    mode: 0600

- name: Generate filebeat.yaml from template on remote
  ansible.builtin.template:
    src: "/tmp/filebeat/filebeat.yaml.j2"
    dest: "/tmp/filebeat/filebeat.yaml"
    mode: 0600

- name: Create ConfigMap YAML on remote
  ansible.builtin.shell: |
    kubectl create configmap filebeat-config \
      --from-file=filebeat.yaml \
      -n {{ namespace }} \
      --dry-run=client -o yaml > filebeat-configmap.yaml
  args:
    chdir: /tmp/filebeat/

- name: Apply ConfigMap on remote
  kubernetes.core.k8s:
    src: /tmp/filebeat/filebeat-configmap.yaml
    namespace: "{{ namespace }}"
    kubeconfig: ~/.kube/config

- name: Apply DaemonSet on remote
  kubernetes.core.k8s:
    src: "{{ k8s_base_path }}/filebeat/filebeat-daemonset.yaml"
    namespace: "{{ namespace }}"
    kubeconfig: ~/.kube/config

- name: Restart Filebeat DaemonSet
  kubernetes.core.k8s:
    kind: DaemonSet
    api_version: apps/v1
    name: filebeat
    namespace: "{{ namespace }}"
    state: restarted
    kubeconfig: ~/.kube/config